name: A workflow for my Hello World file

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  test:
  
    name: Setup bats
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup bats
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1
          
      - name: Copy
        uses: actions/checkout@v1
      - name: give 
        run: sudo chmod 755 ./action-a/entrypoint.sh

      - name: Testing
        run: bats test/testBats.bat
